### ISSUE TITLE
md5 check sum changed

### ISSUE THREAD

**Issue by bergamote** [dev-0x7C6/kinect-audio-setup#1]
The `kinect_fetch_fw` script fails because the md5 check sum is wrong.

I think it can be fixed by changing:

    SDK_MD5="40764fe9e00911bda5095e5be777e311"

to:

    SDK_MD5="945806927702b2c47c32125ab9a80344"

**Comment by dev-0x7C6** [comment]
`kinect_fetch_fw` this script is no longer part of this repository. To provide and install firmware I'm using https://github.com/dev-0x7C6/kinect-audio-firmware with already extracted firmware. Not sure how universal this firmware is, but it's working fine with my first generation kinect device.

**Comment by bergamote** [comment]
Excellent. I thought I'd gotten my version of kinect-audio-setup from here, but obviously I got confused and it was from somewhere else.  
Thing is, the repo packaged version on Ubuntu fails because it depends on `kinect_fetch_fw` (maybe due to the firmware license). I wonder from where they get kinect-audio-setup. Was it from here, but it's an older version in the package?

**Comment by dev-0x7C6** [comment]
> Excellent. I thought I'd gotten my version of kinect-audio-setup from here, but obviously I got confused and it was from somewhere else.
Thing is, the repo packaged version on Ubuntu fails because it depends on kinect_fetch_fw (maybe due to the firmware license). I wonder from where they get kinect-audio-setup. Was it from here, but it's an older version in the package?

I forked it from (since I was unsure about original hosting)
https://git.ao2.it/kinect-audio-setup.git/

Not sure how Ubuntu is taking care of it, maybe you should ask package maintainer directly. They may apply additional patches that aren't part of this repo or even original one.

**Comment by bergamote** [comment]
Thanks for the info, I filed a [bug report](https://bugs.launchpad.net/ubuntu/+source/kinect-audio-setup/+bug/1928152).  
So I suppose now my issue is "readme out of date" ;D
